name: vistony_admin_dashboard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  provider:
  google_fonts:
  flutter_svg:
  fl_chart:
  flutter_bloc:
  http:
  rive:
  dio:
  url_launcher:
  webview_flutter:
  intl:
  cached_network_image:
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/riveAnimations/
